server:
  port: ${WALLET_APP_INNER_PORT}

spring:
  application:
    name: ${WALLET_APP_NAME}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${WALLET_DB_URL}
    username: ${WALLET_DB_USERNAME}
    password: ${WALLET_DB_PASSWORD}